### ISSUE TITLE
Move to private repo?

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/jobboard#6]
I was reviewing minutes from the April board meeting:
"Vance will move the project to a private techlahoma git repo."
https://github.com/techlahoma/board_meetings/blob/master/2016/04_april_minutes.md

I saw no retraction in May's minutes. Does this repo no longer need to be changed to private?

**Comment by vlucas** [comment]
This was a private repo, but I made it public last week. If there are concerns, I can make it private again.

**Comment by seejessicacode** [comment]
I've no concerns. I'm just looking through outstanding issues on Techlahoma
repos before the town hall and noticed that the minutes said that you, Sir
Vancelot, were going to make this repo private. Public is fine with me, but
I don't know if the rest of the board has discussed it though.

**Comment by the-simian** [comment]
yeah at the time of those minutes it was private, and has since come public. I don't think there's anything to worry about. @vlucas  is directing the project, so I think he can handle code visibility as he thinks is necessary

I'm gonna go ahead and close this, yall 👍
