### ISSUE TITLE
Is this still the right repo for the jobs board?

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/jobboard#8]
Is this the repo for http://jobs.techlahoma.org/ ?

If so, let's update the repo description to include a link to http://jobs.techlahoma.org/ and add a link from http://jobs.techlahoma.org/ back to this repo.

**Comment by vlucas** [comment]
Yes, this is the right repo.

**Comment by groovecoder** [comment]
Updated repo website and sent https://github.com/techlahoma/jobboard/pull/9 for a link from site to this repo.
